### ISSUE TITLE
Mảng letters thiếu ký tự 'w'

### ISSUE THREAD

**Issue by thuan1412** [pbcquoc/vietnamese_ocr#2]

**Comment by pbcquoc** [comment]
mảng letters này a xây dựng cho bộ data trong cuộc thi của cinnamon e nhé. nên ko có kí tự đó.

**Comment by thuan1412** [comment]
dạ, tại vì lúc e chạy code của a với bộ data của cinnamon thì bị lỗi do k có kí tự 'w' ạ. E test thử train tập 0825_DataSample 1.

**Comment by pbcquoc** [comment]
e có thể tự bổ sung kí tự w nhé. hoặc sài repo mới này https://github.com/pbcquoc/crnn
