### ISSUE TITLE
Phiên bản các thư viện

### ISSUE THREAD

**Issue by DungLeMTA** [pbcquoc/vietnamese_ocr#4]
Anh Quốc ơi, anh dùng phiên bản tensorflow với Keras gì thế ạ?
Em có thử 1 số version hiện nay nhưng ko được ạ...

**Comment by pbcquoc** [comment]
Hi e, 
Thư viên này không còn support nữa. 
Em có thể sài thư viện mới này của a nhé. 
https://github.com/pbcquoc/vietocr
