### ISSUE TITLE
Ngốn VRAM nhanh quá!

### ISSUE THREAD

**Issue by DungLeMTA** [pbcquoc/vietnamese_ocr#5]
Hello a Cường lại là e đây!
A cho e hỏi là code của file 'loader.py' ấy ạ.
Mình load tất cả ảnh 1 thể, rồi sau đó chia ra làm tập train và tập validation.
Nhưng mà đoạn sau mình lại ko giải phóng đi, do vậy mà lúc train trên colab, VRAM nó bị ngốn quá nhiều a ạ.
Được 2 epoch là out rồi! 

![5017675d5242a71cfe53](https://user-images.githubusercontent.com/69489506/118134903-9f5a7b80-b42c-11eb-9a0a-8c00110b8bfa.jpg)

A có thể chỉ cho e thêm về cách giải phóng bớt dữ liệu để VRAM có thể tải thêm các đợt tiếp theo được ko ạ?
E cám ơn a nhiều ạ!
Dũng

**Comment by pbcquoc** [comment]
Hi e, 
em hãy sử dụng vietocr thay thế cho repo cũ này nhé https://github.com/pbcquoc/vietocr
bên này train/test dễ hơn và cho kết quả tốt hơn đấy.

**Comment by DungLeMTA** [comment]
Vâng e cám ơn a nhiều ạ!
