### ISSUE TITLE
Input Invalid

### ISSUE THREAD

**Issue by ntquyen11** [pbcquoc/vietnamese_ocr#7]
Anh cho e hỏi SIZE là target size và MAX_LEN thì để theo size mong muốn của mình cũng được hay như thế nào ạ?
Em có thấy a comment SIZE là 128,64 và MAX_LEN là 8 nhưng khi khai báo code lại là (2560,160) và 70. Nhưng khi em chạy trên custom dataset thì bị lỗi như này ạ thì em không biết tại sao lại error như thế. Anh giải thích giúp em được không ạ?
![image](https://user-images.githubusercontent.com/73950718/167066617-c4ab2096-7d9c-45a4-b31a-9d0e357392d8.png)

**Comment by pbcquoc** [comment]
Hi e, 
e thử dùng vietocr https://github.com/pbcquoc/vietocr xem sao?
code này a ko còn maintain nữa rồi.

**Comment by ntquyen11** [comment]
@pbcquoc Dạ vâng a. Em cảm ơn a nhiều ạ!
